# Generated by Django 2.2.7 on 2019-11-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=5)),
                ('course_number', models.CharField(max_length=5)),
                ('course_name', models.CharField(max_length=140)),
                ('credit_hours', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('current_role', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=140, verbose_name='Name of University')),
                ('college', models.CharField(max_length=140, verbose_name='College')),
                ('degree', models.CharField(max_length=140, verbose_name='Type of Degree')),
                ('major', models.CharField(max_length=140, verbose_name='Major')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('gpa', models.DecimalField(decimal_places=2, default=4.0, max_digits=4, verbose_name='GPA')),
                ('banner', models.FileField(default='IMAGE URL', upload_to='', verbose_name='Banner Image')),
                ('logo', models.FileField(default='IMAGE URL', upload_to='', verbose_name='Logo')),
                ('m_logo_width', models.PositiveIntegerField(default=50, verbose_name='Mobile Logo Width')),
                ('mascot', models.FileField(default='IMAGE URL', upload_to='', verbose_name='Mascot Image')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Company Name')),
                ('role', models.CharField(max_length=140)),
                ('role_continued', models.CharField(blank=True, max_length=140, null=True, verbose_name='Role (Continued)')),
                ('duration', models.CharField(max_length=40, verbose_name='Date Range')),
                ('short_description', models.TextField()),
                ('long_description', models.TextField(blank=True, null=True, verbose_name='Long Description')),
                ('banner', models.ImageField(upload_to='', verbose_name='Banner Image')),
                ('banner_width', models.PositiveIntegerField(default=300, verbose_name='Banner Width')),
                ('banner_height', models.PositiveIntegerField(default=100, verbose_name='Banner Height')),
                ('tile', models.ImageField(upload_to='', verbose_name='Tile Image')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Extracurriculars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('role', models.CharField(max_length=140)),
                ('role_continued', models.CharField(blank=True, max_length=140, null=True)),
                ('duration', models.CharField(blank=True, max_length=40, null=True, verbose_name='Date Range')),
                ('description', models.TextField(verbose_name='Short Description')),
                ('long', models.TextField(verbose_name='Long Description')),
                ('banner', models.FileField(default='IMAGE URL', upload_to='')),
                ('banner_width', models.PositiveIntegerField(default=300, verbose_name='Banner Width')),
                ('banner_height', models.PositiveIntegerField(default=100, verbose_name='Banner Height')),
                ('tile', models.FileField(default='IMAGE URL', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=140)),
                ('date_of_purchase', models.DateField()),
                ('price_at_purchase', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('role', models.CharField(blank=True, max_length=140, null=True)),
                ('role_continued', models.CharField(blank=True, max_length=140, null=True)),
                ('short', models.TextField()),
                ('long', models.TextField()),
                ('logo', models.FileField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=40)),
                ('definition', models.TextField()),
                ('backstory', models.TextField(default='BACKSTORY')),
                ('typeof', models.IntegerField(blank=True, choices=[(1, 'Programming'), (0, 'Technical')], null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('hover_animation', models.CharField(blank=True, choices=[('back', 'Back'), ('forward', 'Forward'), ('down', 'Down'), ('up', 'Down'), ('spin', 'Spin'), ('drop', 'Drop'), ('fade', 'Fade'), ('float-away', 'Float Away'), ('sink-away', 'Sink Away'), ('grow', 'Grow'), ('shrink', 'Shrink'), ('pulse', 'Pulse'), ('pulse-grow', 'Pulse Grow'), ('pulse-shrink', 'Pulse Shrink'), ('push', 'Push'), ('pop', 'Pop'), ('bounce', 'Bounce'), ('rotate', 'Rotate'), ('grow-rotate', 'Grow Rotate'), ('float', 'Float'), ('sink', 'Sink'), ('bob', 'Bob'), ('hang', 'Hang'), ('wobble-horizontal', 'Wobble Horizontal'), ('wobble-vertical', 'Wobble Vertical'), ('buzz', 'Buzz'), ('buzz-out', 'Buzz Out')], max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('github', models.CharField(max_length=140, verbose_name='GitHub Link')),
                ('sample', models.FileField(blank=True, null=True, upload_to='', verbose_name='Post a picture of your project')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Sample Photo Caption')),
                ('languages', models.ManyToManyField(related_name='boof', to='resume.Languages')),
            ],
        ),
    ]
