# Generated by Django 3.1.4 on 2021-01-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="overview",
            field=models.CharField(default="", max_length=300),
        ),
    ]
