# Generated by Django 2.1.14 on 2019-11-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extracurriculars',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='duration',
        ),
    ]
