# Generated by Django 2.1.14 on 2019-11-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20191129_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Current Role?'),
        ),
    ]
