# Generated by Django 2.1.14 on 2019-11-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_experience_current'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Current',
        ),
    ]
