# Generated by Django 2.1.14 on 2019-12-01 23:07

from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_delete_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('vendor', models.CharField(max_length=60)),
                ('acquired', models.DateField(validators=[resume.models.date_validator_past_only], verbose_name='Acquisiton Date of the Certificate')),
                ('expire', models.DateField(validators=[resume.models.date_validator_future_only], verbose_name='Expiration Date of the Certificate')),
                ('certificate', models.ImageField(upload_to='')),
            ],
        ),
    ]
