# Generated by Django 3.1.4 on 2021-01-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210116_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='certificate',
        ),
    ]
