# Generated by Django 2.1.14 on 2019-12-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifications',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
