# Generated by Django 2.1.14 on 2019-12-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_certifications_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investments',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='banner_height',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='banner_width',
        ),
    ]
