# Generated by Django 2.1.14 on 2019-12-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20191201_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='definition',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='backstory',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='typeof',
        ),
        migrations.AlterField(
            model_name='skills',
            name='logo',
            field=models.FileField(default='pass', upload_to='', verbose_name='Language Logo'),
            preserve_default=False,
        ),
    ]
